---
apiVersion: databaseusersoperator.com/v1alpha1
kind: User
metadata:
  name: john
  namespace: test-database-users-operator
passwordSecret:
  secret:
    name: postgres-john
    namespace: test-database-users-operator
  key: password
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: postgres-john
  namespace: test-database-users-operator
stringData:
  password: TestPassword
