---
apiVersion: databaseusersoperator.com/v1alpha1
kind: User
metadata:
  name: john
spec:
  databases:
    - name: postgres
      passwordSecret:
        key: password
        secret:
          name: postgres-john
          namespace: test-database-users-operator
      privileges:
      - name: some-privileges
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: postgres-john
  namespace: test-database-users-operator
stringData:
  password: TestPassword