---
apiVersion: auth.alex123012.com/v1alpha1
kind: Config
metadata:
  name: cockroachdb
spec:
  databaseType: PostgreSQL
  postgreSQL:
    host: cockroachdb-public
    port: 26257
    namespace: test-database-users-operator
    user: root
    sslMode: verify-full
    sslSecrets:
      userSecret:
        name: cockroachdb-root
        namespace: test-database-users-operator
      caSecret:
        name: cockroachdb-ca
        namespace: test-database-users-operator
---
apiVersion: auth.alex123012.com/v1alpha1
kind: User
metadata:
  name: john
  namespace: test-database-users-operator
spec:
  passwordSecret:
    name: postgres-john
    namespace: test-database-users-operator
  privileges:
    - privilege: UPDATE
      "on": persons
      database: test
    - privilege: SELECT
      "on": persons
      database: test
    - privilege: INSERT
      "on": persons
      database: test
    - privilege: root
  databaseConfig:
    - name: postgres
      namespace: test-database-users-operator
