---
apiVersion: databaseusersoperator.com/v1alpha1
kind: User
metadata:
  name: john
spec:
  databases:
    - name: cockroachdb
      createdSecret:
        name: cockroachdb.client.john
        namespace: test-database-users-operator
      privileges:
      - name: some-privileges
