# permissions for end users to edit databasebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databasebinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: database-users-operator
    app.kubernetes.io/part-of: database-users-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasebinding-editor-role
rules:
- apiGroups:
  - databaseusersoperator.com
  resources:
  - databasebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - databasebindings/status
  verbs:
  - get
