# permissions for end users to view privilegesbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: privilegesbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-users-operator
    app.kubernetes.io/part-of: db-users-operator
    app.kubernetes.io/managed-by: kustomize
  name: privilegesbinding-viewer-role
rules:
- apiGroups:
  - databaseusersoperator.com
  resources:
  - privilegesbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - privilegesbindings/status
  verbs:
  - get
