# permissions for end users to edit privilegesbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: privilegesbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-users-operator
    app.kubernetes.io/part-of: db-users-operator
    app.kubernetes.io/managed-by: kustomize
  name: privilegesbinding-editor-role
rules:
- apiGroups:
  - databaseusersoperator.com
  resources:
  - privilegesbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - privilegesbindings/status
  verbs:
  - get
