---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - databases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - privileges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaseusersoperator.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - databaseusersoperator.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
