contact_links:
  - name: EMAIL
    url: makhonin.a.ru@gmail.com
    about: If you prefer to ask/answer via email.
  - name: TELEGRAM
    url: https://t.me/Alex_makh
    about: If you prefer to ask/answer via telegram.
