---
apiVersion: auth.alex123012.com/v1alpha1
kind: Config
metadata:
  name: cockroachdb
spec:
  databaseType: PostgreSQL
  postgreSQL:
    host: cockroachdb-public
    port: 26257
    namespace: dev
    user: root
    sslMode: verify-full
    sslSecrets:
      userSecret:
        name: cockroachdb-root
        namespace: dev
      caSecret:
        name: cockroachdb-ca
        namespace: dev
---
apiVersion: auth.alex123012.com/v1alpha1
kind: Config
metadata:
  name: postgres
spec:
  databaseType: PostgreSQL
  postgreSQL:
    host: postgres
    port: 5432
    namespace: dev
    user: postgres
    sslMode: disable
    passwordSecret:
      name: postgres
      namespace: dev
