# ---
# apiVersion: auth.alex123012.com/v1alpha1
# kind: User
# metadata:
#   name: cockroachdb-john
# spec:
#   name: "john"
#   privileges:
#     - privilege: SELECT
#       "on": persons
#     - privilege: UPDATE
#       "on": persons
#     - privilege: admin
#   databaseConfig:
#     name: cockroachdb
#     namespace: default
---
apiVersion: auth.alex123012.com/v1alpha1
kind: User
metadata:
  name: postgres-john
spec:
  name: "john"
  passwordSecret:
    name: postgres-john
    namespace: default
  privileges:
    - privilege: CREATE
      database: test
    - privilege: UPDATE
      "on": persons
      database: test
    - privilege: postgres
  databaseConfig:
    - name: postgres
      namespace: default
