name: E2E tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  e2e-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.20.0
          cluster_name: e2e-tests
          node_image: kindest/node:v1.26.6

      - name: Setup operator
        run: make prepare-kind

      - name: Run E2E
        run: make run-e2e