name: E2E tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  e2e-run:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.20.0
          node_image: kindest/node:v1.26.6

      - name: Setup operator
        run: make prepare-kind